version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:12.1
    volumes:
      - /data/postgresdb:/var/lib/postgresql/data
    ports:
      - 9300:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: departmentsDbAngular
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

