
spring:
  datasource:
    url: jdbc:postgresql://localhost:9300/departmentsDbAngular
    username: postgres
    password: root

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

logging:
  level:
    root: info

