#Mail wild.bill.java.man@gmail.com
#Password {wild.bill.java.man=1}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/departmentsDbAngular
    username: postgres
    password: root

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  jackson:
    default-property-inclusion: non_null
    serialization:
       indent-output: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: wild.bill.java.man@gmail.com
    password: gsphzwvboyietpcf
    port: 587
    properties:
      mail:
        smtp:
          #from: wild.bill.java.man@gmail.com
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
    protocol: smtp
    test-connection: false

logging:
  level:
    root: info

jwt:
   secretKey: secretKey
   validityPeriod: 3600000
